# Pair Group By y Apply

{% file src="<https://931940412-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FiDkWIWBqfl4XxuhVbroM%2Fuploads%2Fgit-blob-963fb44c546e52a6e1c26e0ef8cdb09ad290486b%2Fworld_data_full.csv?alt=media>" %}
Descarga este Jupyter y ábrelo en VS Code.
{% endfile %}

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("world_data_full.csv", index_col = 0)
df.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude
0,Afghanistan,60,AF,58.1,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.3,AFN,4.47,2.1,0.70,"19,101,353,833",104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,"38,041,754",48.9,9.3,71.4,11.12,"9,797,273",33.93911,67.709953
1,Albania,105,AL,43.1,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.4,ALL,1.62,28.1,1.36,"15,278,077,447",107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,"2,854,191",55.7,18.6,36.6,12.33,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.4,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.0,DZD,3.02,0.8,0.28,"169,988,236,398",109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,"43,053,054",41.2,37.2,66.1,11.70,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.0,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.0,1.51,"3,154,057,987",106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.5,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.1,AOA,5.52,46.3,0.97,"94,635,415,870",113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,"31,825,295",77.5,9.2,49.1,6.89,"21,061,025",-11.202692,17.873887


## **Ejercicios apply**

1. Las columnas `land_area`, `armed_forces_size`, `co2-emissions`, `gdp`, `population`, `urban_population`, `latitude`, `longitude`, `density`, `cpi` son de tipo object pero en realidad deberían ser numéricas. Crea una función que nos permita cambiar el tipo de dato de estas columnas al que le corresponde.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   country                               195 non-null    object
 1   density                               195 non-null    object
 2   abbreviation                          188 non-null    object
 3   agricultural_land                     188 non-null    float64
 4   land_area                             194 non-null    object
 5   armed_forces_size                     171 non-null    object
 6   birth_rate                            189 non-null    float64
 7   calling_code                          194 non-null    float64
 8   capital/major_city                    192 non-null    object
 9   co2-emissions                         188 non-null    object
 10  cpi                                   178 non-null    object
 11  cpi_change                            179 non-null    float64
 12  currency-code                         180 non-null    object
 13  fertility_rate                        188 non-null    float64
 14  forested_area                         188 non-null    float64
 15  gasoline_price                        175 non-null    float64
 16  gdp                                   193 non-null    object
 17  gross_primary_education_enrollment    188 non-null    float64
 18  gross_tertiary_education_enrollment   183 non-null    float64
 19  infant_mortality                      189 non-null    float64
 20  largest_city                          189 non-null    object
 21  life_expectancy                       187 non-null    float64
 22  maternal_mortality_ratio              181 non-null    float64
 23  minimum_wage                          150 non-null    float64
 24  official_language                     190 non-null    object
 25  out_of_pocket_health_expenditure      188 non-null    float64
 26  physicians_per_thousand               188 non-null    float64
 27  population                            194 non-null    object
 28  population_labor_force_participation  176 non-null    float64
 29  tax_revenue                           169 non-null    float64
 30  total_tax_rate                        183 non-null    float64
 31  unemployment_rate                     176 non-null    float64
 32  urban_population                      190 non-null    object
 33  latitude                              195 non-null    object
 34  longitude                             195 non-null    object
dtypes: float64(19), object(16)
memory usage: 54.8+ KB

In [5]:
for col in df:
    df[col].unique()
    print(col)
    print(df[col].unique())
    print("--------------------")

country
['Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Australia' 'Austria'
 'Azerbaijan' 'The Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi'
 'Ivory Coast' 'Cape Verde' 'Cambodia' 'Cameroon' 'Canada'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Republic of the Congo' 'Costa Rica' 'Croatia' 'Cuba' 'Cyprus'
 'Czech Republic' 'Democratic Republic of the Congo' 'Denmark' 'Djibouti'
 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Fiji'
 'Finland' 'France' 'Gabon' 'The Gambia' 'Georgia' 'Germany' 'Ghana'
 'Greece' 'Grenada' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Vatican City' 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Republic of Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan'
 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania'
 'Luxembourg' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Mauritania' 'Mauritius' 'Mexico'
 'Federated States of Micronesia' 'Moldova' 'Monaco' 'Mongolia'
 'Montenegro' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal'
 'Netherlands' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North Korea'
 'North Macedonia' 'Norway' 'Oman' 'Pakistan' 'Palau'
 'Palestinian National Authority' 'Panama' 'Papua New Guinea' 'Paraguay'
 'Peru' 'Philippines' 'Poland' 'Portugal' 'Qatar' 'Romania' 'Russia'
 'Rwanda' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino' 'S�����������'
 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore'
 'Slovakia' 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa'
 'South Korea' 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan' 'Suriname'
 'Sweden' 'Switzerland' 'Syria' 'Tajikistan' 'Tanzania' 'Thailand'
 'East Timor' 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey'
 'Turkmenistan' 'Tuvalu' 'Uganda' 'Ukraine' 'United Arab Emirates'
 'United Kingdom' 'United States' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Venezuela' 'Vietnam' 'Yemen' 'Zambia' 'Zimbabwe']
--------------------
density
['60' '105' '18' '164' '26' '223' '17' '104' '3' '109' '123' '39' '2,239'
 '1,265' '668' '47' '383' '108' '20' '11' '64' '4' '25' '83' '76' '463'
 '138' '95' '56' '8' '13' '153' '46' '467' '16' '100' '73' '106' '131'
 '139' '40' '137' '43' '96' '225' '71' '103' '313' '50' '35' '31' '67'
 '115' '49' '119' '9' '239' '57' '240' '81' '331' '167' '53' '70' '414'
 '2,003' '89' '107' '464' '151' '52' '93' '72' '400' '206' '273' '347' '7'
 '94' '147' '34' '32' '30' '667' '238' '242' '48' '203' '99' '1,802'
 '1,380' '329' '5' '626' '66' '784' '26,337' '2' '541' '508' '55' '19'
 '226' '214' '15' '287' '847' '58' '368' '124' '111' '248' '84' '525'
 '205' '301' '284' '566' '228' '87' '8,358' '114' '527' '341' '219' '68'
 '152' '110' '393' '229' '75' '118' '281' '36' '79' '314' '38']
--------------------
abbreviation
['AF' 'AL' 'DZ' 'AD' 'AO' 'AG' 'AR' 'AM' 'AU' 'AT' 'AZ' 'BS' 'BH' 'BD'
 'BB' 'BY' 'BE' 'BZ' 'BJ' 'BT' 'BO' 'BA' 'BW' 'BR' 'BN' 'BG' 'BF' 'BI'
 'CI' 'CV' 'KH' 'CM' 'CA' 'CF' 'TD' 'CL' 'CN' 'CO' 'KM' nan 'CR' 'HR' 'CU'
 'CY' 'CZ' 'CD' 'DK' 'DJ' 'DM' 'DO' 'EC' 'EG' 'SV' 'GQ' 'ER' 'EE' 'ET'
 'FJ' 'FI' 'FR' 'GA' 'GM' 'GE' 'DE' 'GH' 'GR' 'GD' 'GT' 'GN' 'GW' 'GY'
 'HT' 'HN' 'HU' 'IS' 'IN' 'ID' 'IR' 'IQ' 'IL' 'IT' 'JM' 'JP' 'JO' 'KZ'
 'KE' 'KI' 'KW' 'KG' 'LA' 'LV' 'LB' 'LS' 'LR' 'LY' 'LI' 'LT' 'LU' 'MG'
 'MW' 'MY' 'MV' 'ML' 'MT' 'MH' 'MR' 'MU' 'MX' 'FM' 'MD' 'MC' 'MN' 'ME'
 'MA' 'MZ' 'MM' 'NR' 'NP' 'NL' 'NZ' 'NI' 'NE' 'NG' 'KP' 'NO' 'OM' 'PK'
 'PW' 'PA' 'PG' 'PY' 'PE' 'PH' 'PL' 'PT' 'QA' 'RO' 'RU' 'RW' 'KN' 'LC'
 'VC' 'WS' 'SM' 'ST' 'SA' 'SN' 'RS' 'SC' 'SL' 'SG' 'SK' 'SI' 'SB' 'SO'
 'ZA' 'KR' 'SS' 'ES' 'LK' 'SD' 'SR' 'SE' 'CH' 'SY' 'TJ' 'TZ' 'TH' 'TL'
 'TG' 'TO' 'TT' 'TN' 'TR' 'TM' 'TV' 'UG' 'UA' 'AE' 'GB' 'US' 'UY' 'UZ'
 'VU' 'VE' 'VN' 'YE' 'ZM' 'ZW']
--------------------
agricultural_land
[58.1 43.1 17.4 40.  47.5 20.5 54.3 58.9 48.2 32.4 57.7  1.4 11.1 70.6
 23.3 42.  44.6  7.  33.3 13.6 34.8 45.6 33.9  2.7 46.3 44.2 79.2 64.8
 19.6 30.9 20.6  6.9  8.2 39.7 21.2 56.2 40.3 71.5 31.1 34.5 27.6 59.9
 12.2 45.2 11.6 62.  73.4 48.7 22.2  3.8 76.4 10.1 75.2 23.1  nan 36.3
  7.5 52.4 20.  59.8 47.7 69.  47.6 23.5 36.  59.  58.   8.6 66.8 28.9
 58.4 18.7 60.4 31.5 28.2 21.4 64.5 24.6 43.2 41.  12.3 12.  80.4 48.5
  8.4 55.  10.3 64.3 77.6 28.   8.7 32.2 47.2 53.7 71.2 61.4 26.3 33.8
 63.9 38.5 42.4 54.6 31.4 74.2 19.  68.5 63.5 19.5 47.1 28.7 53.3 40.5
 42.1 36.1 77.7 21.8  4.6 47.8 10.9 30.4  2.6 55.1 18.5 41.7 46.9 39.5
  5.8 58.8 13.3 25.6 12.4 16.7 50.7 80.8 46.1 39.3  3.4 54.7  0.9 39.2
 30.7  3.9 70.3 79.8 52.6 43.7  0.6  7.4 38.4 75.8 34.1 44.8 43.3 70.2
 45.8 10.5 49.8 72.  60.  71.9 71.7  5.5 44.4 82.6 62.9 15.3 24.5 32.1
 41.9]
--------------------
land_area
['652,230' '28,748' '2,381,741' '468' '1,246,700' '443' '2,780,400'
 '29,743' '7,741,220' '83,871' '86,600' '13,880' '765' '148,460' '430'
 '207,600' '30,528' '22,966' '112,622' '38,394' '1,098,581' '51,197'
 '581,730' '8,515,770' '5,765' '110,879' '274,200' '27,830' '322,463'
 '4,033' '181,035' '475,440' '9,984,670' '622,984' '1,284,000' '756,096'
 '9,596,960' '1,138,910' '2,235' '342,000' '51,100' '56,594' '110,860'
 '9,251' '78,867' '2,344,858' '43,094' '23,200' '751' '48,670' '283,561'
 '1,001,450' '21,041' '28,051' '117,600' '45,228' '17,364' '1,104,300'
 '18,274' '338,145' '643,801' '267,667' '11,300' '69,700' '357,022'
 '238,533' '131,957' '349' '108,889' '245,857' '36,125' '214,969' '27,750'
 '0' '112,090' '93,028' '103,000' '3,287,263' '1,904,569' '1,648,195'
 '438,317' '70,273' '20,770' '301,340' '10,991' '377,944' '89,342'
 '2,724,900' '580,367' '811' '17,818' '199,951' '236,800' '64,589'
 '10,400' '30,355' '111,369' '1,759,540' '160' '65,300' '2,586' '587,041'
 '118,484' '329,847' '298' '1,240,192' '316' '181' '1,030,700' '2,040'
 '1,964,375' '702' '33,851' '2' '1,564,116' '13,812' '446,550' '799,380'
 '676,578' '824,292' '21' '147,181' '41,543' '268,838' '130,370'
 '1,267,000' '923,768' '120,538' '25,713' '323,802' '309,500' '796,095'
 '459' nan '75,420' '462,840' '406,752' '1,285,216' '300,000' '312,685'
 '92,212' '11,586' '238,391' '17,098,240' '26,338' '261' '616' '389'
 '2,831' '61' '964' '2,149,690' '196,722' '77,474' '455' '71,740' '716'
 '49,035' '20,273' '28,896' '637,657' '1,219,090' '99,720' '644,329'
 '505,370' '65,610' '1,861,484' '163,820' '450,295' '41,277' '185,180'
 '144,100' '947,300' '513,120' '14,874' '56,785' '747' '5,128' '163,610'
 '783,562' '488,100' '26' '241,038' '603,550' '83,600' '243,610'
 '9,833,517' '176,215' '447,400' '12,189' '912,050' '331,210' '527,968'
 '752,618' '390,757']
--------------------
armed_forces_size
['323,000' '9,000' '317,000' nan '117,000' '0' '105,000' '49,000' '58,000'
 '21,000' '82,000' '1,000' '19,000' '221,000' '155,000' '32,000' '2,000'
 '12,000' '6,000' '71,000' '11,000' '730,000' '8,000' '31,000' '27,000'
 '191,000' '24,000' '72,000' '35,000' '122,000' '2,695,000' '481,000'
 '10,000' '18,000' '76,000' '16,000' '23,000' '134,000' '15,000' '13,000'
 '41,000' '836,000' '42,000' '202,000' '138,000' '4,000' '25,000'
 '307,000' '7,000' '26,000' '180,000' '146,000' '43,000' '3,000' '40,000'
 '3,031,000' '676,000' '563,000' '209,000' '178,000' '347,000' '261,000'
 '116,000' '29,000' '129,000' '80,000' '34,000' '22,000' '136,000' '5,000'
 '336,000' '246,000' '513,000' '112,000' '215,000' '1,469,000' '47,000'
 '936,000' '158,000' '153,000' '52,000' '126,000' '1,454,000' '252,000'
 '81,000' '20,000' '634,000' '185,000' '196,000' '124,000' '30,000'
 '239,000' '17,000' '28,000' '455,000' '48,000' '512,000' '46,000'
 '297,000' '63,000' '148,000' '1,359,000' '68,000' '343,000' '522,000'
 '51,000']
--------------------
birth_rate
[32.49 11.78 24.28  7.2  40.73 15.33 17.02 13.99 12.6   9.7  14.   13.97
 18.18 10.65  9.9  10.3  20.79 36.22 17.26 21.75  8.11 24.82 13.92 14.9
  8.9  37.93 39.01 35.74 19.49 22.46 35.39 10.1  35.35 42.17 12.43 10.9
 14.88 31.88 32.86  9.   10.17 10.46 10.7  41.18 10.6  21.47 12.   19.51
 19.72 26.38 18.25 33.24 30.3    nan 32.34 21.28  8.6  11.3  31.61 38.54
 13.47  9.5  29.41  8.1  16.47 24.56 36.36 35.13 19.97 24.35 21.6   9.6
 17.86 18.07 18.78 29.08 12.5  20.8   7.3  16.1   7.4  21.98 21.77 28.75
 27.89 13.94 27.1  23.55 10.   17.55 26.81 33.04 18.83 32.66 34.12 16.75
 14.2  41.54  9.2  29.03 33.69 10.2  17.6  22.82  5.9  24.13 11.73 18.94
 37.52 28.64 19.89 11.98 20.64 46.08 37.91 13.89 10.4  19.19 28.25 18.98
 27.07 20.57 17.95 20.55  8.5   9.54 11.5  31.7  14.24 24.38  6.8  31.54
 17.8  34.52 17.1  33.41  8.8   9.4  32.44 41.75 20.51  6.4  35.01  7.9
 15.83 32.18 18.54 11.4  23.69 30.76 36.7  10.34 29.42 33.11 24.3  12.94
 17.56 16.03 23.83 38.14  8.7  10.33 11.   11.6  13.86 23.3  29.6  17.88
 30.45 36.19 30.68]
--------------------
calling_code
[9.300e+01 3.550e+02 2.130e+02 3.760e+02 2.440e+02 1.000e+00 5.400e+01
 3.740e+02 6.100e+01 4.300e+01 9.940e+02 9.730e+02 8.800e+02 3.750e+02
 3.200e+01 5.010e+02 2.290e+02 9.750e+02 5.910e+02 3.870e+02 2.670e+02
 5.500e+01 6.730e+02 3.590e+02 2.260e+02 2.570e+02 2.250e+02 2.380e+02
 8.550e+02 2.370e+02 2.360e+02 2.350e+02 5.600e+01 8.600e+01 5.700e+01
 2.690e+02 2.420e+02 5.060e+02 3.850e+02 5.300e+01 3.570e+02 4.200e+02
 2.430e+02 4.500e+01 2.530e+02 5.930e+02 2.000e+01 5.030e+02 2.400e+02
 2.910e+02 3.720e+02 2.680e+02 2.510e+02 6.790e+02 3.580e+02 3.300e+01
 2.410e+02 2.200e+02 9.950e+02 4.900e+01 2.330e+02 3.000e+01 5.020e+02
 2.240e+02 2.450e+02 5.920e+02 5.090e+02 3.790e+02 5.040e+02 3.600e+01
 3.540e+02 9.100e+01 6.200e+01 9.800e+01 9.640e+02 3.530e+02 9.720e+02
 3.900e+01 1.876e+03 8.100e+01 9.620e+02 7.000e+00 2.540e+02 6.860e+02
 9.650e+02 9.960e+02 8.560e+02 3.710e+02 9.610e+02 2.660e+02 2.310e+02
 2.180e+02 4.230e+02 3.700e+02 3.520e+02 2.610e+02 2.650e+02 6.000e+01
 9.600e+02 2.230e+02 3.560e+02 6.920e+02 2.220e+02 2.300e+02 5.200e+01
 6.910e+02 3.730e+02 3.770e+02 9.760e+02 3.820e+02 2.120e+02 2.580e+02
 9.500e+01 2.640e+02 6.740e+02 9.770e+02 3.100e+01 6.400e+01 5.050e+02
 2.270e+02 2.340e+02 8.500e+02 3.890e+02 4.700e+01 9.680e+02 9.200e+01
 6.800e+02       nan 5.070e+02 6.750e+02 5.950e+02 5.100e+01 6.300e+01
 4.800e+01 3.510e+02 9.740e+02 4.000e+01 2.500e+02 6.850e+02 3.780e+02
 2.390e+02 9.660e+02 2.210e+02 3.810e+02 2.480e+02 2.320e+02 6.500e+01
 4.210e+02 3.860e+02 6.770e+02 2.520e+02 2.700e+01 8.200e+01 2.110e+02
 3.400e+01 9.400e+01 2.490e+02 5.970e+02 4.600e+01 4.100e+01 9.630e+02
 9.920e+02 2.550e+02 6.600e+01 6.700e+02 2.280e+02 6.760e+02 2.160e+02
 9.000e+01 9.930e+02 6.880e+02 2.560e+02 3.800e+02 9.710e+02 4.400e+01
 5.980e+02 9.980e+02 6.780e+02 5.800e+01 8.400e+01 9.670e+02 2.600e+02
 2.630e+02]
--------------------
capital/major_city
['Kabul' 'Tirana' 'Algiers' 'Andorra la Vella' 'Luanda'
 "St. John's, Saint John" 'Buenos Aires' 'Yerevan' 'Canberra' 'Vienna'
 'Baku' 'Nassau, Bahamas' 'Manama' 'Dhaka' 'Bridgetown' 'Minsk'
 'City of Brussels' 'Belmopan' 'Porto-Novo' 'Thimphu' 'Sucre' 'Sarajevo'
 'Gaborone' 'Bras���' 'Bandar Seri Begawan' 'Sofia' 'Ouagadougou'
 'Bujumbura' 'Yamoussoukro' 'Praia' 'Phnom Penh' 'Yaound�' 'Ottawa'
 'Bangui' "N'Djamena" 'Santiago' 'Beijing' 'Bogot�' 'Moroni, Comoros'
 'Brazzaville' 'San Jos������' 'Zagreb' 'Havana' 'Nicosia' 'Prague'
 'Kinshasa' 'Copenhagen' 'Djibouti City' 'Roseau' 'Santo Domingo' 'Quito'
 'Cairo' 'San Salvador' 'Malabo' 'Asmara' 'Tallinn' 'Mbabane'
 'Addis Ababa' 'Suva' 'Helsinki' 'Paris' 'Libreville' 'Banjul' 'Tbilisi'
 'Berlin' 'Accra' 'Athens' "St. George's, Grenada" 'Guatemala City'
 'Conakry' 'Bissau' 'Georgetown, Guyana' 'Port-au-Prince' 'Vatican City'
 'Tegucigalpa' 'Budapest' 'Reykjav��' 'New Delhi' 'Jakarta' 'Tehran'
 'Baghdad' 'Dublin' 'Jerusalem' 'Rome' 'Kingston, Jamaica' 'Tokyo' 'Amman'
 'Astana' 'Nairobi' 'South Tarawa' 'Kuwait City' 'Bishkek' 'Vientiane'
 'Riga' 'Beirut' 'Maseru' 'Monrovia' nan 'Vaduz' 'Vilnius'
 'Luxembourg City' 'Antananarivo' 'Lilongwe' 'Kuala Lumpur' 'Mal�'
 'Bamako' 'Valletta' 'Majuro' 'Nouakchott' 'Port Louis' 'Mexico City'
 'Palikir' 'Chi����' 'Monaco City' 'Ulaanbaatar' 'Podgorica' 'Rabat'
 'Maputo' 'Naypyidaw' 'Windhoek' 'Yaren District' 'Kathmandu' 'Amsterdam'
 'Wellington' 'Managua' 'Niamey' 'Abuja' 'Pyongyang' 'Skopje' 'Oslo'
 'Muscat' 'Islamabad' 'Ngerulmud' 'Panama City' 'Port Moresby' 'Asunci��'
 'Lima' 'Manila' 'Warsaw' 'Lisbon' 'Doha' 'Bucharest' 'Moscow' 'Kigali'
 'Basseterre' 'Castries' 'Kingstown' 'Apia' 'City of San Marino' 'S����'
 'Riyadh' 'Dakar' 'Belgrade' 'Victoria, Seychelles' 'Freetown'
 'Bratislava' 'Ljubljana' 'Honiara' 'Mogadishu' 'Pretoria' 'Seoul' 'Juba'
 'Madrid' 'Colombo' 'Khartoum' 'Paramaribo' 'Stockholm' 'Bern' 'Damascus'
 'Dushanbe' 'Dodoma' 'Bangkok' 'Dili' 'Lom�' 'Nuku����' 'Port of Spain'
 'Tunis' 'Ankara' 'Ashgabat' 'Funafuti' 'Kampala' 'Kyiv' 'Abu Dhabi'
 'London' 'Washington, D.C.' 'Montevideo' 'Tashkent' 'Port Vila' 'Caracas'
 'Hanoi' 'Sanaa' 'Lusaka' 'Harare']
--------------------
co2-emissions
['8,672' '4,536' '150,006' '469' '34,693' '557' '201,348' '5,156'
 '375,908' '61,448' '37,620' '1,786' '31,694' '84,246' '1,276' '58,280'
 '96,889' '568' '6,476' '1,261' '21,606' '21,848' '6,340' '462,299'
 '7,664' '41,708' '3,418' '495' '9,674' '543' '9,919' '8,291' '544,894'
 '297' '1,016' '85,822' '9,893,038' '97,814' '202' '3,282' '8,023'
 '17,488' '28,284' '6,626' '102,218' '2,021' '31,786' '620' '180' '25,258'
 '41,155' '238,560' '7,169' '5,655' '711' '16,590' nan '14,870' '2,046'
 '45,871' '303,276' '5,321' '532' '10,128' '727,973' '16,670' '62,434'
 '268' '16,777' '2,996' '293' '2,384' '2,978' '9,813' '45,537' '2,065'
 '2,407,672' '563,325' '661,710' '190,061' '37,711' '65,166' '320,411'
 '8,225' '1,135,886' '25,108' '247,207' '17,910' '66' '98,734' '9,787'
 '17,763' '7,004' '24,796' '2,512' '1,386' '50,564' '51' '12,963' '8,988'
 '3,905' '1,298' '248,289' '1,445' '3,179' '1,342' '143' '2,739' '4,349'
 '486,406' '5,115' '25,368' '2,017' '61,276' '7,943' '25,280' '4,228'
 '9,105' '170,780' '34,382' '5,592' '120,369' '41,023' '63,457' '201,150'
 '224' '10,715' '7,536' '7,407' '57,414' '122,287' '299,037' '48,742'
 '103,259' '69,259' '1,732,027' '1,115' '238' '414' '220' '246' '121'
 '563,449' '10,902' '45,221' '605' '1,093' '37,535' '32,424' '12,633'
 '169' '645' '476,644' '620,302' '1,727' '244,002' '23,362' '20,000'
 '1,738' '43,252' '34,477' '28,830' '5,310' '11,973' '283,763' '3,000'
 '128' '43,868' '29,937' '372,725' '70,630' '11' '5,680' '202,250'
 '206,324' '379,025' '5,006,302' '6,766' '91,811' '147' '164,175'
 '192,668' '10,609' '5,141' '10,983']
--------------------
cpi
['149.9' '119.05' '151.36' nan '261.73' '113.81' '232.75' '129.18' '119.8'
 '118.06' '156.32' '116.22' '117.59' '179.68' '134.09' '117.11' '105.68'
 '110.71' '167.18' '148.32' '104.9' '149.75' '167.4' '99.03' '114.42'
 '106.58' '182.11' '111.61' '110.5' '127.63' '118.65' '116.76' '186.86'
 '117.7' '131.91' '125.08' '140.95' '103.62' '124.74' '128.85' '109.82'
 '102.51' '116.48' '133.85' '110.35' '120.25' '103.87' '135.5' '124.14'
 '288.57' '111.23' '124.35' '122.14' '143.86' '132.3' '112.33' '110.05'
 '122.19' '172.73' '133.61' '112.85' '268.36' '101.87' '107.43' '142.92'
 '262.95' '111.65' '116.19' '179.29' '150.34' '121.64' '129' '180.44'
 '151.18' '550.93' '119.86' '108.15' '110.62' '162.47' '105.48' '125.6'
 '182.75' '180.51' '99.55' '126.6' '155.68' '135.87' '116.86' '130.02'
 '155.86' '223.13' '125.71' '118.38' '115.09' '184.33' '418.34' '121.46'
 '99.7' '108.73' '113.45' '135.02' '129.91' '141.54' '112.1' '166.2'
 '195.76' '116.32' '111.07' '182.31' '168.18' '157.97' '188.73' '115.91'
 '114.24' '162.74' '109.32' '267.51' '120.27' '113.53' '182.32' '118.17'
 '122.07' '155.99' '143.82' '129.78' '129.61' '114.11' '115.38' '123.78'
 '180.75' '151.09' '104.57' '110.13' '109.67' '117.56' '110.63' '185.09'
 '118.4' '109.25' '144' '129.96' '234.16' '114.41' '115.34' '111.05'
 '133.06' '158.93' '115.16' '4,583.71' '110.96' '155.53' '1,344.19'
 '294.66' '110.51' '143.2' '148.57' '187.43' '113.27' '145.38' '113.3'
 '121.09' '141.75' '155.33' '234.44' '173.87' '281.66' '114.52' '119.62'
 '117.24' '202.92' '117.13' '2,740.27' '163.52' '157.58' '212.31' '105.51']
--------------------
cpi_change
[ 2.300e+00  1.400e+00  2.000e+00        nan  1.710e+01  1.200e+00
  5.350e+01  1.600e+00  1.500e+00  2.600e+00  2.500e+00  2.100e+00
  5.600e+00  4.100e+00 -9.000e-01  2.700e+00  1.800e+00  6.000e-01
  2.800e+00  3.700e+00 -4.000e-01  3.100e+00 -3.200e+00 -7.000e-01
  1.100e+00  1.900e+00  3.710e+01 -1.000e+00  2.900e+00  3.500e+00
 -4.300e+00  2.200e+00  8.000e-01  3.000e-01  3.300e+00  1.000e+00
  9.200e+00  1.000e-01  1.580e+01  7.100e+00  4.900e+00  7.200e+00
  2.000e-01  9.500e+00  1.250e+01  4.400e+00  3.000e+00  7.700e+00
  3.990e+01  4.000e-01  9.000e-01  3.900e+00  5.000e-01  5.200e+00
  4.700e+00  2.360e+01  1.700e+00  9.400e+00  7.000e-01 -1.700e+00
  3.600e+00  4.800e+00  7.300e+00  8.800e+00  5.400e+00 -2.500e+00
  1.140e+01  1.060e+01  1.300e+00  3.800e+00  4.500e+00  3.400e+00
  7.900e+00 -1.200e+00  1.480e+01  1.879e+02  5.100e+01  2.200e+01
  3.670e+01  6.000e+00  7.400e+00  6.700e+00  1.520e+01 -1.900e+00
  7.500e+00  2.549e+02  8.100e+00]
--------------------
currency-code
['AFN' 'ALL' 'DZD' 'EUR' 'AOA' 'XCD' 'ARS' 'AMD' 'AUD' 'AZN' nan 'BHD'
 'BDT' 'BBD' 'BYN' 'BZD' 'XOF' 'BOB' 'BAM' 'BWP' 'BRL' 'BND' 'BGN' 'BIF'
 'CVE' 'XAF' 'CAD' 'CLP' 'CNY' 'COP' 'KMF' 'CRC' 'HRK' 'CUP' 'CZK' 'CDF'
 'DKK' 'DJF' 'DOP' 'USD' 'EGP' 'ERN' 'ETB' 'FJD' 'GMD' 'GEL' 'GHS' 'GTQ'
 'GNF' 'GYD' 'HTG' 'HNL' 'HUF' 'ISK' 'INR' 'IDR' 'IRR' 'IQD' 'ILS' 'JMD'
 'JOD' 'KZT' 'KES' 'KWD' 'KGS' 'LAK' 'LBP' 'LYD' 'CHF' 'MGA' 'MWK' 'MYR'
 'MRU' 'MUR' 'MXN' 'MDL' 'MNT' 'MAD' 'MZN' 'MMK' 'NPR' 'NZD' 'NIO' 'NGN'
 'KPW' 'MKD' 'NOK' 'OMR' 'PKR' 'PGK' 'PYG' 'PEN' 'PHP' 'PLN' 'QAR' 'RON'
 'RUB' 'RWF' 'WST' 'STN' 'SAR' 'RSD' 'SCR' 'SLL' 'SGD' 'SBD' 'SOS' 'ZAR'
 'KRW' 'SSP' 'LKR' 'SDG' 'SRD' 'SEK' 'SYP' 'TJS' 'TZS' 'THB' 'TOP' 'TTD'
 'TND' 'TRY' 'TMT' 'UGX' 'UAH' 'AED' 'GBP' 'UYU' 'UZS' 'VUV' 'VED' 'VND'
 'YER' 'ZMW']
--------------------
fertility_rate
[4.47 1.62 3.02 1.27 5.52 1.99 2.26 1.76 1.74 1.47 1.73 1.75 2.04 1.45
 2.31 4.84 1.98 2.73 2.87 1.85 1.56 5.19 5.41 4.65 2.27 2.5  4.57 1.5
 4.72 5.75 1.65 1.69 1.81 4.21 4.43 1.33 5.92 1.9  2.35 2.43 3.33 4.51
 4.06 1.59  nan 4.25 2.77 1.41 1.88 3.97 5.22 2.06 3.87 1.35 4.7  4.48
 2.46 2.94 1.54 1.71 2.22 2.14 3.67 3.09 1.29 1.42 2.76 2.84 3.49 3.57
 2.08 3.3  2.67 1.6  2.09 3.14 4.32 2.24 1.44 1.63 1.37 4.08 2.   1.87
 5.88 1.23 4.05 4.56 2.13 3.05 1.26 2.9  2.42 4.85 2.15 3.4  1.92 2.4
 6.91 5.39 2.89 3.51 2.21 3.56 2.25 2.58 1.46 1.38 1.57 4.04 2.11 1.89
 3.88 2.32 4.63 1.49 2.41 4.26 1.14 1.52 4.4  6.07 0.98 2.2  4.41 2.81
 3.59 4.89 1.53 4.02 2.07 2.79 4.96 1.3  1.68 1.97 3.78 2.05 3.79 3.62]
--------------------
forested_area
[ 2.1 28.1  0.8 34.  46.3 22.3  9.8 11.7 16.3 46.9 14.1 51.4 11.  14.7
 42.6 22.6 59.7 37.8 72.5 50.3 42.7 18.9 58.9 72.1 35.4 19.3 10.9 32.7
 22.5 52.9 39.3 38.2 35.6  3.8 24.3 22.4 52.7 19.7 65.4 54.6 34.4 31.3
 18.7 34.6 67.2  0.2 57.4 41.7 50.2  0.1 12.6 55.5 14.9 51.3  nan 12.5
 55.9 73.1 31.2 90.  48.4 40.6 41.2 31.7 50.  25.8 69.8 83.9  3.5 40.
 22.9  0.5 23.8 49.9  6.6  1.9  7.7 31.8 30.9 68.5  1.1  1.2  7.8 15.
  0.4  3.3 82.1 54.  13.4  1.6 43.1 34.8 35.7 21.4 33.2 67.6 70.2 19.
 33.9 91.9  8.  61.5 48.  43.6  8.3 25.4 11.2 38.6 25.9  0.9  7.2 40.7
  0.  87.6 61.9 74.1 37.7 57.7 27.8 30.1 49.8 42.3 69.2 60.4 55.8 42.8
 31.1 88.4 23.1 40.4 62.  77.9 10.   7.6 63.4 36.9 32.9  8.1 98.3 68.9
  2.7  3.  51.6 32.2 45.4  3.1 46.   6.8 15.4  8.8 33.3  9.7 16.7  4.6
 13.1 10.7  7.5 36.1 48.1  1.  65.2 35.5]
--------------------
gasoline_price
[0.7  1.36 0.28 1.51 0.97 0.99 1.1  0.77 0.93 1.2  0.56 0.92 0.43 1.12

In [6]:
def cambiar_tipo(x):
        x = str(x)
        x = x.replace(",", "")
        x = x.replace(" ", "")
        return pd.to_numeric(x, errors = "coerce")

In [7]:
columnas = ["land_area", "armed_forces_size", "co2-emissions", "gdp", "population", "urban_population", "latitude", "longitude", "density", "cpi"]

for col in columnas:
    df[col] = df[col].apply(cambiar_tipo)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   country                               195 non-null    object
 1   density                               195 non-null    int64
 2   abbreviation                          188 non-null    object
 3   agricultural_land                     188 non-null    float64
 4   land_area                             194 non-null    float64
 5   armed_forces_size                     171 non-null    float64
 6   birth_rate                            189 non-null    float64
 7   calling_code                          194 non-null    float64
 8   capital/major_city                    192 non-null    object
 9   co2-emissions                         188 non-null    float64
 10  cpi                                   178 non-null    float64
 11  cpi_change                            179 non-null    float64
 12  currency-code                         180 non-null    object
 13  fertility_rate                        188 non-null    float64
 14  forested_area                         188 non-null    float64
 15  gasoline_price                        175 non-null    float64
 16  gdp                                   193 non-null    float64
 17  gross_primary_education_enrollment    188 non-null    float64
 18  gross_tertiary_education_enrollment   183 non-null    float64
 19  infant_mortality                      189 non-null    float64
 20  largest_city                          189 non-null    object
 21  life_expectancy                       187 non-null    float64
 22  maternal_mortality_ratio              181 non-null    float64
 23  minimum_wage                          150 non-null    float64
 24  official_language                     190 non-null    object
 25  out_of_pocket_health_expenditure      188 non-null    float64
 26  physicians_per_thousand               188 non-null    float64
 27  population                            194 non-null    float64
 28  population_labor_force_participation  176 non-null    float64
 29  tax_revenue                           169 non-null    float64
 30  total_tax_rate                        183 non-null    float64
 31  unemployment_rate                     176 non-null    float64
 32  urban_population                      190 non-null    float64
 33  latitude                              194 non-null    float64
 34  longitude                             194 non-null    float64
dtypes: float64(28), int64(1), object(6)
memory usage: 54.8+ KB

In [8]:
df.sample(5)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude
51,Egypt,103,EG,3.8,1001450.0,836000.0,26.38,20.0,Cairo,238560.0,288.57,9.2,EGP,3.33,0.1,0.40,3.031751e+11,106.3,35.2,18.1,Cairo,71.8,37.0,NaN,Modern Standard Arabic,62.0,0.45,100388073.0,46.4,12.5,44.4,10.76,42895824.0,26.820553,30.802498
8,Australia,3,AU,48.2,7741220.0,58000.0,12.60,61.0,Canberra,375908.0,119.80,1.6,AUD,1.74,16.3,0.93,1.392681e+12,100.3,113.1,3.1,Sydney,82.7,6.0,13.59,NaN,19.6,3.68,25766605.0,65.5,23.0,47.4,5.27,21844756.0,-25.274398,133.775136
47,Djibouti,43,DJ,73.4,23200.0,13000.0,21.47,253.0,Djibouti City,620.0,120.25,3.3,DJF,2.73,0.2,1.32,3.318716e+09,75.3,5.3,49.8,Djibouti City,66.6,248.0,NaN,French,20.4,0.22,973560.0,60.2,NaN,37.9,10.30,758549.0,11.825138,42.590275
171,Tajikistan,68,TJ,34.1,144100.0,17000.0,30.76,992.0,Dushanbe,5310.0,148.57,6.0,TJS,3.59,3.0,0.71,8.116627e+09,100.9,31.3,30.4,Dushanbe,70.9,17.0,0.23,Persian,63.1,1.70,9321018.0,42.0,9.8,67.3,11.02,2545477.0,38.861034,71.276093
68,Guatemala,167,GT,36.0,108889.0,43000.0,24.56,502.0,Guatemala City,16777.0,142.92,3.7,GTQ,2.87,32.7,0.79,7.671039e+10,101.9,21.8,22.1,Guatemala City,74.1,95.0,1.60,Spanish,55.8,0.35,16604026.0,62.3,10.6,35.2,2.46,8540945.0,15.783471,-90.230759

2. Crea una función para añadir una nueva columna llamada 'Continent' al DataFrame para indicar a qué continente pertenece cada país.

In [9]:
continent_dict = {
    "Europe": [
        "Albania", "Andorra", "Austria", "Belarus", "Belgium",
        "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Cyprus",
        "Czech Republic", "Denmark", "Estonia", "Finland", "France",
        "Germany", "Greece", "Hungary", "Iceland", "Republic of Ireland",
        "Italy", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg",
        "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands",
        "North Macedonia", "Norway", "Poland", "Portugal", "Romania",
        "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia",
        "Spain", "Sweden", "Switzerland", "Ukraine",
        "United Kingdom", "Vatican City"
    ],

    "Africa": [
        "Algeria", "Angola", "Benin", "Botswana", "Burkina Faso",
        "Burundi", "Ivory Coast", "Cape Verde", "Cameroon",
        "Central African Republic", "Chad", "Comoros",
        "Republic of the Congo", "Democratic Republic of the Congo",
        "Djibouti", "Egypt", "Equatorial Guinea", "Eritrea",
        "Eswatini", "Ethiopia", "Gabon", "The Gambia", "Ghana",
        "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia",
        "Libya", "Madagascar", "Malawi", "Mali", "Mauritania",
        "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger",
        "Nigeria", "Rwanda", "Senegal", "Seychelles",
        "Sierra Leone", "Somalia", "South Africa", "South Sudan",
        "Sudan", "Tanzania", "Togo", "Tunisia", "Uganda",
        "Zambia", "Zimbabwe"
    ],

    "Asia": [
        "Afghanistan", "Armenia", "Azerbaijan", "Bahrain",
        "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China",
        "Georgia", "India", "Indonesia", "Iran", "Iraq", "Israel",
        "Japan", "Jordan", "Kazakhstan", "Kuwait", "Kyrgyzstan",
        "Laos", "Lebanon", "Malaysia", "Maldives", "Mongolia",
        "Myanmar", "Nepal", "North Korea", "Oman", "Pakistan",
        "Philippines", "Qatar", "Saudi Arabia", "Singapore",
        "South Korea", "Sri Lanka", "Syria", "Tajikistan",
        "Thailand", "East Timor", "Turkey", "Turkmenistan",
        "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen",
        "Palestinian National Authority"
    ],

    "North America": [
        "Antigua and Barbuda", "The Bahamas", "Barbados", "Belize",
        "Canada", "Costa Rica", "Cuba", "Dominica",
        "Dominican Republic", "El Salvador", "Grenada",
        "Guatemala", "Haiti", "Honduras", "Jamaica", "Mexico",
        "Nicaragua", "Panama", "Saint Kitts and Nevis",
        "Saint Lucia", "Saint Vincent and the Grenadines",
        "Trinidad and Tobago", "United States"
    ],

    "South America": [
        "Argentina", "Bolivia", "Brazil", "Chile", "Colombia",
        "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname",
        "Uruguay", "Venezuela"
    ],

    "Oceania": [
        "Australia", "Fiji", "Kiribati", "Marshall Islands",
        "Federated States of Micronesia", "Nauru",
        "New Zealand", "Palau", "Papua New Guinea", "Samoa",
        "Solomon Islands", "Tonga", "Tuvalu", "Vanuatu"
    ]
}

In [10]:
def obtener_continente(pais):
    for continente, paises in continent_dict.items():
        if pais in paises:
            return continente
    return None

df["Continent"] = df["country"].apply(obtener_continente)

In [11]:
df.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,Continent
0,Afghanistan,60,AF,58.1,652230.0,323000.0,32.49,93.0,Kabul,8672.0,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,38041754.0,48.9,9.3,71.4,11.12,9797273.0,33.939110,67.709953,Asia
1,Albania,105,AL,43.1,28748.0,9000.0,11.78,355.0,Tirana,4536.0,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,2854191.0,55.7,18.6,36.6,12.33,1747593.0,41.153332,20.168331,Europe
2,Algeria,18,DZ,17.4,2381741.0,317000.0,24.28,213.0,Algiers,150006.0,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,43053054.0,41.2,37.2,66.1,11.70,31510100.0,28.033886,1.659626,Africa
3,Andorra,164,AD,40.0,468.0,NaN,7.20,376.0,Andorra la Vella,469.0,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77142.0,NaN,NaN,NaN,NaN,67873.0,42.506285,1.521801,Europe
4,Angola,26,AO,47.5,1246700.0,117000.0,40.73,244.0,Luanda,34693.0,261.73,17.1,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,31825295.0,77.5,9.2,49.1,6.89,21061025.0,-11.202692,17.873887,Africa

3. Guarda el DataFrame después de los cambios creados después de los dos ejercicios anteriores para usarlo posteriormente.

In [13]:
df.to_csv("world_data_full_2.csv")


## **Ejercicios groupby**

1. ¿Cuál es la densidad de población promedio por continente?

In [36]:
df.head(4)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude
0,Afghanistan,60,AF,58.1,652230.0,323000.0,32.49,93.0,Kabul,8672.0,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,38041754.0,48.9,9.3,71.4,11.12,9797273.0,33.939110,67.709953
1,Albania,105,AL,43.1,28748.0,9000.0,11.78,355.0,Tirana,4536.0,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,2854191.0,55.7,18.6,36.6,12.33,1747593.0,41.153332,20.168331
2,Algeria,18,DZ,17.4,2381741.0,317000.0,24.28,213.0,Algiers,150006.0,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,43053054.0,41.2,37.2,66.1,11.70,31510100.0,28.033886,1.659626
3,Andorra,164,AD,40.0,468.0,NaN,7.20,376.0,Andorra la Vella,469.0,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77142.0,NaN,NaN,NaN,NaN,67873.0,42.506285,1.521801

In [37]:
df.groupby("country")["density"].mean().reset_index()

         country  density
0    Afghanistan     60.0
1        Albania    105.0
2        Algeria     18.0
3        Andorra    164.0
4         Angola     26.0
..           ...      ...
190    Venezuela     32.0
191      Vietnam    314.0
192        Yemen     56.0
193       Zambia     25.0
194     Zimbabwe     38.0

[195 rows x 2 columns]

2. ¿Cuál es la esperanza de vida promedio por idioma oficial? Agrupa los países por idioma oficial y calcula la esperanza de vida promedio.

In [38]:
df.groupby("official_language")["life_expectancy"].mean().reset_index()

    official_language  life_expectancy
0           Afrikaans        63.900000
1            Albanian        78.500000
2             Amharic        66.200000
3              Arabic        72.864706
4            Armenian        74.900000
..                ...              ...
71  Tuvaluan Language              NaN
72          Ukrainian        71.600000
73               Urdu        67.100000
74              Uzbek        71.600000
75         Vietnamese        75.300000

[76 rows x 2 columns]

In [14]:
df.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,Continent
0,Afghanistan,60,AF,58.1,652230.0,323000.0,32.49,93.0,Kabul,8672.0,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,38041754.0,48.9,9.3,71.4,11.12,9797273.0,33.939110,67.709953,Asia
1,Albania,105,AL,43.1,28748.0,9000.0,11.78,355.0,Tirana,4536.0,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,2854191.0,55.7,18.6,36.6,12.33,1747593.0,41.153332,20.168331,Europe
2,Algeria,18,DZ,17.4,2381741.0,317000.0,24.28,213.0,Algiers,150006.0,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,43053054.0,41.2,37.2,66.1,11.70,31510100.0,28.033886,1.659626,Africa
3,Andorra,164,AD,40.0,468.0,NaN,7.20,376.0,Andorra la Vella,469.0,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77142.0,NaN,NaN,NaN,NaN,67873.0,42.506285,1.521801,Europe
4,Angola,26,AO,47.5,1246700.0,117000.0,40.73,244.0,Luanda,34693.0,261.73,17.1,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,31825295.0,77.5,9.2,49.1,6.89,21061025.0,-11.202692,17.873887,Africa

3. ¿Cuál es la tasa de mortalidad infantil promedio por moneda?

In [16]:
df.groupby('currency-code')['infant_mortality'].mean().reset_index().round(2).sort_values(by='infant_mortality', ascending=False)

    currency-code  infant_mortality
104           SLL              78.5
105           SOS              76.6
81            NGN              75.7
21            CDF              68.2
43            GNF              64.9
..            ...               ...
103           SGD               2.3
102           SEK               2.2
83            NOK               2.1
55            ISK               1.5
72            MKD               NaN

[133 rows x 2 columns]

4. ¿Cuál es el salario mínimo por continente?

In [20]:
df.groupby('Continent')['minimum_wage'].min().reset_index()

       Continent  minimum_wage
0         Africa          0.01
1           Asia          0.05
2         Europe          0.31
3  North America          0.05
4        Oceania          0.40
5  South America          0.01

5. ¿Cuál es la tasa de impuestos total máxima por densidad de población por continente? Para solucionar este ejercicio puedes:
   * Primero, necesitas calcular la tasa de impuestos total para cada continente. La tasa de impuestos total se encuentra en la columna "total\_tax\_rate".
   * Luego, calcula la densidad de población para cada continente. La densidad de población se encuentra en la columna "density".
   * Ahora, divide la tasa de impuestos total entre la densidad de población para obtener la tasa de impuestos total por persona por kilómetro cuadrado.
   * Encuentra el país que tiene el valor más alto en esta nueva columna calculada.

In [22]:
df_media_tax = df.groupby('Continent')['total_tax_rate'].mean().reset_index()

In [23]:
df_media_density = df.groupby('Continent')['density'].mean().reset_index()

6. ¿Cuál es el porcentaje de población urbana promedio por continente?
7. ¿Cuál es la diferencia entre el PIB promedio y el gasto en salud de bolsillo promedio por idioma oficial? Para contestar esta pregunta dabes seguir los siguientes pasos:
   * Agrupa el DataFrame por idioma oficial y calcula la media del Gasto de Bolsillo en salud (`out_of_pocket_health_expenditure`) y del GPD.
   * Calcula la diferencia entre el PIB promedio y el gasto en salud de bolsillo promedio
8. ¿Cuál es la tasa de maternidad promedio por tasa de impuestos total? Para resolver el ejercicio deberás:
   * Primero, calcula la tasa de maternidad promedio para cada continente. Puedes usar la columna "maternal\_mortality\_ratio" que representa la tasa de mortalidad materna.
   * Calcula la tasa de impuestos total promedio para cada continente. Puedes usar la columna "total\_tax\_rate" que representa la tasa de impuestos total en cada continente.
   * Luego, divide la tasa de maternidad promedio por la tasa de impuestos total promedio para obtener la relación entre ambas tasas.
   * Encuentra el país con la tasa de maternidad más alta por punto porcentual de tasa de impuestos total.
9. Ejercicios **bonus** groupby:
   * ¿Cuál es la tasa de natalidad máxima por área forestal por continente? Encuentra el país con la tasa de natalidad más alta por cada punto porcentual de área forestal.
   * ¿Cuál es la diferencia entre la tasa de impuestos total y la tasa de desempleo promedio por continente?